# -*- coding: utf-8 -*-
"""Sobol_Sequence_Generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10xxNoaqhWMkFRytIBm2OI_cToR2sdfXo
"""

import pandas as pd
from scipy.stats import qmc

# --- 1. Define Your Experiment Parameters ---

# Number of points in the pattern
n_points = 10
# Number of continuous dimensions (Power, Speed, Radius)
n_dims = 3

# Define the bounds for your continuous variables
# Format: 'Variable': [min_value, max_value]
bounds = {
    'Power_W_mm2': [50, 300],
    'Speed_mm_s': [5, 50],
    'Radius_mm': [0.8, 1.5]
}

# Extract lower and upper bounds for the scaler function
lower_bounds = [bounds[key][0] for key in bounds]
upper_bounds = [bounds[key][1] for key in bounds]
column_names = list(bounds.keys())

print(f"Generating a {n_points}-point, {n_dims}-dimensional Sobol sequence.")
print("Using bounds:")
print(f"  Power:  {bounds['Power_W_mm2']} W/mm²")
print(f"  Speed:  {bounds['Speed_mm_s']} mm/s")
print(f"  Radius: {bounds['Radius_mm']} mm")
print("-" * 30)

# --- 2. Generate the Sobol Sequence ---

# Initialize the Sobol sequence generator
# We set scramble=True, which is standard practice to improve the sequence's properties
sampler = qmc.Sobol(d=n_dims, scramble=True)

# Generate the n_points in the unit cube [0, 1]
samples_unit = sampler.random(n=n_points)

# --- 3. Scale the Sequence to Your Bounds ---

# Scale the unit cube samples to your real-world bounds
samples_scaled = qmc.scale(samples_unit, lower_bounds, upper_bounds)

# --- 4. Format as a Clean Table (10-Point Pattern) ---

# Convert to a pandas DataFrame for easy viewing and rounding
df_pattern = pd.DataFrame(samples_scaled, columns=column_names)

# Round to 2 decimal places for practical use
df_pattern_rounded = df_pattern.round(2)

print("\n--- Your 10-Point Continuous Parameter Pattern ---")
# Using to_string() ensures it prints all rows neatly
print(df_pattern_rounded.to_string(index=False))
print("-" * 30)

# --- 5. Generate the Full 50-Run DoE Table ---

# Create the list of 5 materials
materials = ['HEA_1'] * n_points + \
            ['HEA_2'] * n_points + \
            ['HEA_3'] * n_points + \
            ['HEA_4'] * n_points + \
            ['HEA_5'] * n_points

# Tile the 10-point pattern 5 times
df_full = pd.concat([df_pattern_rounded] * 5, ignore_index=True)

# Add the Material column
df_full['Material'] = materials

# Reorder columns to put Material first
df_full = df_full[['Material'] + column_names]

# Add blank columns for your output data
df_full['Y1_Max_Prin_Stress'] = ""
df_full['Y2_Max_Von_Mises'] = ""
df_full['Y3_Max_Temp'] = ""
# Add any other output columns you need
df_full['Y4_Other_Output'] = ""

# Add a run number for clarity
df_full.index = df_full.index + 1
df_full.index.name = "Run"

print("\n--- Full 50-Run Design of Experiments Table ---")
# Print the full table
# We use to_string() to ensure Colab prints the entire 50-row table
print(df_full.to_string())
print("-" * 30)

# --- 6. Save to Excel ---
output_filename = 'doe_50_run_plan.xlsx'
df_full.to_excel(output_filename)

print(f"\nSUCCESS: The full 50-run plan has been saved to '{output_filename}'.")
print("You can find this file in the Colab file explorer on the left.")